tasks:
  - init: yarn install && yarn run build
#  - command: npm run ng serve
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-vsliveshare.vsliveshare-pack@0.3.4:SHAGljo8pKUdyOKmsw+SXw==